<h2 style="color:white"><center> Ejercicios Numpy - Estadisctica <center><h2>

In [1]:
import numpy as np
import random

<p><b># Ejercicio 1:</b> Crea un arreglo NumPy de 10 números enteros aleatorios, comprendidos entre 0-100. Debes calcular la media, la mediana, la desviación estándar, la varianza y el valor máximo y minimo del arreglo con sus respectivas posiciones.<p>

In [9]:
random_list = np.random.randint(0,101,size=9) # Crea un array de 10 numeros enteros entre 0 y 100

mean = np.mean(random_list)     # Calcula la media aritmetica del arreglo "random_list"
median = np.median(random_list) # Calcula la mediana del arreglo "random_list"
std = np.std(random_list)       # Calcula la desviacion estandar de arreglo "random_list"
var = np.var(random_list)       # Calcula la varianza del arreglo "random_list"

value_max = np.max(random_list)        # Devuelve el numero de mayor valor del arreglo "random_list"
pos_value_max = np.argmax(random_list) # Devuelve la posicion del valor maximo del arreglo "random_list"
value_min = np.min(random_list)        # Devuelve el numero de menor valor del arreglo "random_list"
pos_value_min = np.argmin(random_list) # Devuelve la posicion del valor minimo del arreglo "random_list"

print("#### EJERCICIO - 01 ####\n")
print(f'Arreglo: {random_list} | Tipo: {type(random_list)}')
print(f'Media arit.: {mean}')
print(f'Mediana: {median}')
print(f'Desv. estandar: {std}')
print(f'Varianza: {var}')
print(f'N° mayor: {value_max} | Posicion: {pos_value_max}')
print(f'N° menor: {value_min} | Posicion: {pos_value_min}')

#### EJERCICIO - 01 ####

Arreglo: [61 65 11 87 74 61 41 82 33] | Tipo: <class 'numpy.ndarray'>
Media arit.: 57.22222222222222
Mediana: 61.0
Desv. estandar: 23.232055334423777
Varianza: 539.7283950617283
N° mayor: 87 | Posicion: 3
N° menor: 11 | Posicion: 2


<p><b># Ejercicio 2:</b> Crea dos matrices de 3x3 NumPy. Debes calcular la suma, resta, multiplicacion y division de ambas matrices y mostrar el resultado.<p>

In [18]:
matriz_1 = np.array( [[1,2,3], [4,5,6], [7,8,9]] )          # Crea una matriz 3x3
matriz_2 = np.array( [[10,20,30], [40,50,60], [70,80,90]] ) # Crea una matriz 3x3

suma = matriz_1 + matriz_2   # Suma de 2 matrices
resta =  matriz_1 - matriz_2 # Resta de 2 matrices
multi =  matriz_1 * matriz_2 # Producto de 2 matrices
div =  matriz_1 / matriz_2   # Cociente de 2 matrices

print('#### EJERCICIO - 02 ####\n')
print('Matriz 1')
print(matriz_1)
print('\nMatriz 2')
print(matriz_2)

print(f'\nSuma: {suma}')
print(f'\nResta: {resta}')
print(f'\nProducto: {multi}')
print(f'\nCociente: {div}')



#### EJERCICIO - 02 ####

Matriz 1
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz 2
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Suma: [[11 22 33]
 [44 55 66]
 [77 88 99]]

Resta: [[ -9 -18 -27]
 [-36 -45 -54]
 [-63 -72 -81]]

Producto: [[ 10  40  90]
 [160 250 360]
 [490 640 810]]

Cociente: [[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]


<p><b># Ejercicio 3:</b> Crea una matriz de 5x5 llena de unos. Luego, crea una copia y cambia el valor de los elementos de la copia. En los bordes cero y en el centro un 5<p>

In [41]:
matriz = np.ones((5,5)) # Crea una matriz 5x5 rellena de unos
matriz_copy = matriz.copy()    # Realiza una copia de la matriz

matriz_copy[0, :] = 0  # Transforma la primera columna en ceros
matriz_copy[-1, :] = 0 # Transforma la ultima columna en ceros
matriz_copy[:, 0] = 0  # Transforma la primera fila en ceros
matriz_copy[:, -1] = 0 # Transforma la ultima fila en ceros
matriz_copy[2,2] = 5   # Transforma el numero central en 5

print('#### EJERCICIO - 03 ####\n')
print('Matriz original')
print(matriz)

print('\nMatriz duplicado')
print(matriz_copy)

#### EJERCICIO - 03 ####

Matriz original
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Matriz duplicado
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 5. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


<p><b># Ejercicio 4:</b> Crea una matriz de 4x4 con cualquier valor que desees. Luego, cambia la forma de la matriz a 2x8 y aplana la matriz a 1D.<p>

In [44]:
matriz = np.array( [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]] )

matriz_2x8 = matriz.reshape(2,8) # Cambia la forma de la matriz a 2x8
matriz_1d = matriz.flatten() # Aplana la matriz a una dimension

print('#### EJERCICIO - 04 ####\n')
print(f'Matriz:\n{matriz}')
print(f'\nMatriz 2x8:\n{matriz_2x8}')
print(f'\nMatriz 1D:\n{matriz_1d}')


#### EJERCICIO - 04 ####

Matriz:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Matriz 2x8:
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]

Matriz 1D:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


<p><b># Ejercicio 5:</b> Genera una secuencia de números entre 0 y 1 con un paso de 0.01. Luego, calcula e imprime la suma de todos los números en la secuencia.<p>

In [48]:
num_sec = np.arange(0, 1, 0.01)
num_sec_sum = np.sum(num_sec)

print('#### EJERCICIO - 05 ####\n')
print(f'Secuencia:\n{num_sec}')
print(f'Sumatoria: {num_sec_sum}')

#### EJERCICIO - 05 ####

Secuencia:
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]
Sumatoria: 49.49999999999999
